name: Docker Image Makefile CI (new)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build on ubuntu-latest armv7
    steps:
    - uses: actions/checkout@v3
    
    - name: Build docker images
      with:
        arch: armv7
        distro: ubuntu-latest
        run: make build-all

    - name: Run tests
      shell: 'script -q -e -c "bash {0}"'
      run: |
        make test-all
